### ISSUE TITLE
Error 403 when accessing baikal admin page

### ISSUE THREAD

**Issue by alfureu** [bjuretko/docker-baikal-infcloud#17] opened 2019-04-29 15:42 UTC
I am getting error 403 when accessing [http://localhost:8800/baikal/html/admin/ ](http://localhost:8800/baikal/html/admin/). It seems that the directory has been made as admin, while the docker does not have such priviledges. Deleting and re-creating the WEBROOT/docker-baikal-infcloud/baikal solved it. 

The same is happening when creating the database: 
```
Validation error
The FOLDER containing the DB file is not writable, and it has to.
Please give write permissions on folder /var/www/baikal/Specific/db
```

This make me think, would it be possible to build and also run it with GID 100 UID 1000 by default, setting it in ENV?

**Comment by alfureu** [comment] 2019-04-29 15:56
FYI, I believe, due to reading permission I am also unable to login to the infcloud frontend

**Comment by bjuretko** [comment] 2019-04-29 22:23
I cannot reproduce this behaviour on a fresh checkout (MacOS).
These are the file permissions *in* the container:

```
/var/www $ ls -lah
total 24
drwxr-xr-x    1 lighttpd nobody      4.0K Apr 29 23:45 .
drwxr-xr-x    1 root     root        4.0K Apr 29 23:45 ..
drwxr-xr-x    1 lighttpd nobody      4.0K Apr 29 23:45 .well-known
drwxr-xr-x    1 lighttpd nobody      4.0K Apr 26 20:54 baikal
drwxr-xr-x    1 lighttpd nobody      4.0K Apr 29 23:45 infcloud
drwxr-xr-x    1 lighttpd nobody      4.0K Apr 29 23:45 localhost
/var/www $ ls -lah baikal/
total 68
drwxr-xr-x    1 lighttpd nobody      4.0K Apr 26 20:54 .
drwxr-xr-x    1 lighttpd nobody      4.0K Apr 29 23:45 ..
-rw-r--r--    1 lighttpd nobody      5.0K Apr 23 15:54 CHANGELOG.md
drwxr-xr-x    1 lighttpd nobody      4.0K Apr 23 15:55 Core
-rw-r--r--    1 lighttpd nobody     34.3K Apr 23 00:12 LICENSE
-rw-r--r--    1 lighttpd nobody       687 Apr 23 15:55 README.md
drwxr-xr-x    7 nobody   nobody       224 Apr 30 00:17 Specific
drwxr-xr-x    1 lighttpd nobody      4.0K Apr 24 18:51 html
drwxr-xr-x    1 lighttpd nobody      4.0K Apr 26 20:54 vendor
/var/www $ ls -lah baikal/Specific/
total 16
drwxr-xr-x    7 nobody   nobody       224 Apr 30 00:17 .
drwxr-xr-x    1 lighttpd nobody      4.0K Apr 26 20:54 ..
-rw-r--r--    1 nobody   nobody        31 Apr 30 00:16 .htaccess
-rw-r--r--    1 nobody   nobody         0 Apr 30 00:17 INSTALL_DISABLED
-rw-r--r--    1 nobody   nobody      1.7K Apr 30 00:17 config.php
-rw-r--r--    1 nobody   nobody      2.3K Apr 30 00:17 config.system.php
drwxr-xr-x    4 nobody   nobody       128 Apr 30 00:17 db
/var/www $ ls -lah baikal/Specific/db/
total 108
drwxr-xr-x    4 nobody   nobody       128 Apr 30 00:17 .
drwxr-xr-x    7 nobody   nobody       224 Apr 30 00:17 ..
-rw-r--r--    1 nobody   nobody         0 Apr 30 00:15 .keep
-rw-r--r--    1 nobody   nobody    108.0K Apr 30 00:17 db.sqlite
```
The shared volume is owned by nobody:nobody and therefore has write permissions.
This is mapped to my host folder (where the docker engine has write permissions as well)

Can you recheck with the current master branch with running `make` and `make run` ?

**Comment by bjuretko** [comment] 2019-04-29 22:46
I could reproduce it on another system, will look into it.

**Comment by bjuretko** [comment] 2019-05-01 17:20
@DOFfactory  you could check out master which is working on my local system and  NAS.

**Comment by bjuretko** [comment] 2019-05-03 21:29
I will close it for now and reopen the issue if problem may still exist for others.

**Closed as completed by bjuretko** 2019-05-03 21:29 UTC

**Comment by DOFfactory** [comment] 2019-05-03 22:30
Hi, just checked with the latest version. The problem persists on Asustor NAS, where the `docker` command can be called only as `sudo docker build`. I believe this is the culprit as all the folders and files are then created with `admin:administrator` uid:gid. Since you then create the `nobody:nobody`, I assume it does not have then reading access to the DB and to the web files.

**Comment by alfureu** [comment] 2019-05-03 23:31
I can confirm it works. Thanks for this.
